apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "direktiv.fullname" . }}-ingress
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    {{- if ne .Values.ingress.certificate "none" }}
    ingress.kubernetes.io/force-ssl-redirect: "true"
    {{- end }}
    projectcontour.io/response-timeout: {{ .Values.ingress.timeout }}
spec:
  {{- if ne .Values.ingress.certificate "none" }}
  tls:
  - hosts:
      - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.certificate }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: {{ include "direktiv.fullname" . }}-api-service
              port:
                number: 8080
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "direktiv.fullname" . }}-ui
              port:
                number: 8080
