{{ if .Values.ingress.crt }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.secret.name }}
  namespace: {{ .Values.ingress.secret.namespace }}
data:
  tls.crt: {{ .Values.ingress.crt | b64enc | quote }}
  tls.key: {{ .Values.ingress.key | b64enc | quote }}
{{ end }}
