kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: {{ include "direktiv.serviceAccountName" . }}-role-cluster
 labels:
   {{- include "direktiv.labels" . | nindent 4 }}
rules:
- apiGroups: ["serving.knative.dev"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "update", "delete", "create"]
