apiVersion: v1
kind: Secret
metadata:
  name: {{ include "direktiv.fullname" . }}-secrets-isolate
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.isolates.db }}
  db: {{ .Values.isolates.db | b64enc | quote }}
  {{- else }}
  db: {{ printf "host=%s-support port=5432 user=direktiv dbname=direktiv password=direktivdirektiv sslmode=disable" ( include "direktiv.fullname" . )  | b64enc | quote }}
  {{- end }}
