kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-sidecar-grpc-back
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "direktiv.name" . }}
  ingress:
  - from:
    - podSelector:
        matchExpressions:
          - { key: serving.knative.dev/configurationGeneration, operator: Exists }
    ports:
      - port: 7777
