kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-ui-ingress
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "direktiv.name" . }}-ui
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: envoy
      namespaceSelector:
        matchLabels:
          networking.knative.dev/ingress-provider: contour
    ports:
      - port: 8080
