kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-support
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "direktiv.name" . }}-support
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ include "direktiv.name" . }}
    ports:
      - port: 5432
