kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: {{ include "direktiv.serviceAccountName" . }}-prometheus-role
 labels:
   {{- include "direktiv.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
