{{- if or (eq .Values.withUI true) (eq .Values.withFlow true) (eq .Values.withIsolate true) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "direktiv.fullname" . }}
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.withIsolate }}
  {{- if .Values.isolate.minio.secretKey }}
  minioAccessKey: {{ .Values.isolate.minio.accessKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.isolate.minio.secretKey }}
  minioSecretKey: {{ .Values.isolate.minio.secretKey | b64enc | quote }}
  {{- end }} {{- end }}
  {{- if .Values.db }}
  db: {{ .Values.db | b64enc | quote }}
  {{- else }}
  db: {{ printf "host=%s-support port=5432 user=direktiv dbname=direktiv password=direktivdirektiv sslmode=disable" ( include "direktiv.fullname" . ) | b64enc | quote }}
  {{- end}}
  {{- if .Values.flow.secretsDb  }}
  secretsDb: {{ .Values.flow.secretsDb | b64enc | quote }}
  {{- else }}
  secretsDb: {{ printf "host=%s-support port=5432 user=direktiv dbname=direktiv password=direktivdirektiv sslmode=disable" ( include "direktiv.fullname" . ) | b64enc | quote }}
  {{- end}}
  {{- end}}
