{{- if (eq .Values.withFlow true)}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "direktiv.fullname" . }}
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.db }}
  db: {{ .Values.db | b64enc | quote }}
  {{- else }}
  db: {{ printf "host=%s-support port=5432 user=direktiv dbname=direktiv password=direktivdirektiv sslmode=disable" ( include "direktiv.fullname" . )  | b64enc | quote }}
  {{- end}}
  {{- if .Values.secrets.db  }}
  secretsDb: {{ .Values.secrets.db | b64enc | quote }}
  {{- else }}
  secretsDb: {{ printf "host=%s-support port=5432 user=direktiv dbname=direktiv password=direktivdirektiv sslmode=disable" ( include "direktiv.fullname" . )  | b64enc | quote }}
  {{- end}}
  key: {{ .Values.secrets.key  | b64enc | quote }}
  {{- end}}
