{{- if .Values.withUI -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "direktiv.fullname" . }}-ui
  labels:
    {{- include "direktiv.labelsUI" . | nindent 4 }}
spec:
  type: {{ .Values.ui.portType }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: ui
      {{- if (eq .Values.ui.portType "NodePort") }}
      nodePort: {{ int .Values.ui.nodePort }}
      {{- end }}
  selector:
    {{- include "direktiv.selectorLabelsUI" . | nindent 4 }}
{{- end }}
