name: API test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        test-section:
          - api
          - engine
          - errors
          - events
          - filesystem
          - functions
          - gateway
          - logparser
          - mirror
          - namespace
          - registry
          - secrets
          - secrets2
          - services
          - variables
          - variables2

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run tests
        run: TEST_SECTION=${{ matrix.test-section }} make docker-e2e-api
