name: "Build Container Components"
on:
  workflow_dispatch:
    inputs:
      tag:
  push:
    tags:
      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.0
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: test version
        run: |
          echo ${{ env.RELEASE_VERSION }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: build containers
        run: |
          export RV=${{ env.RELEASE_VERSION }}
          echo "RV set to $RV"
          if [ "$RV" == "main" ] || [ "$RV" == "" ] ; then export RV=latest; fi
          echo "RV set to $RV"
          make push DOCKER_REPO=direktiv RELEASE=$RV
          make push DOCKER_REPO=direktiv RELEASE=latest
