name: Build Container Components
on:
  workflow_dispatch:
  create:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: test version
      run: |
        echo ${{ env.RELEASE_VERSION }}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: build containers
      uses: addnab/docker-run-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.io
        image: chekote/node:14.8.0-alpine
        options: -v ${{ github.workspace }}:/work
        run: |
          echo "Building UI"
          cd /work/ui/frontend
          yarn install
          NODE_ENV=production yarn build
    - name: build containers
      run: |
        export RV=${{ env.RELEASE_VERSION }}
        echo "RV set to $RV"
        if [ "$RV" == "main" ] || [ "$RV" == "" ] ; then export RV=latest; fi
        echo "RV set to $RV"
        make docker-isolate
        make docker-secrets
        make docker-flow
        make docker-cli
        echo "Copying Built UI Files over"
        cp -r ui/frontend/build  build/docker/ui
        make docker-ui
        echo "containers built"
        docker tag direktiv-flow vorteil/flow:$RV
        docker tag direktiv-isolate vorteil/isolate:$RV
        docker tag direktiv-secrets vorteil/secrets:$RV
        docker tag direktiv-cli vorteil/direkcli:$RV
        docker tag direktiv-ui vorteil/ui:$RV
        docker tag direktiv-ui vorteil/ui
        docker image list
        docker push vorteil/flow:$RV
        docker push vorteil/isolate:$RV
        docker push vorteil/secrets:$RV
        docker push vorteil/direkcli:$RV
        docker push vorteil/ui:$RV
        docker push vorteil/ui
