name: (UI) Test Playwright
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '*'
      - '!ui/**'

jobs:
  test:
    timeout-minutes: 45
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ui

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18.18.1

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: |
            ../
          key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile') }}

      - name: Build direktiv
        run: |
          docker build -t direktiv-dev ../.
          docker compose -f ../docker-compose.yaml up -d --scale e2e-tests=0
        env:
          DIREKTIV_UI_IMAGE: nginx
          DIREKTIV_IMAGE: direktiv-dev
      # Cache Node Modules
      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-modules-${{ runner.os }}-

      - name: Install yarn
        run: npm install -g yarn
      - name: Install project dependencies
        run: yarn

      # Cache Playwright Browsers
      - name: Cache Playwright Browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            playwright-browsers-${{ runner.os }}-
      - name: Dependencies Playwright dry run
        run: yarn playwright install-deps --dry-run
      - name: Install Playwright Browsers
        run: yarn playwright install

      - name: Run Playwright tests
        run: yarn playwright test
        env:
          VITE_E2E_UI_HOST: "http://localhost"
          VITE_E2E_UI_PORT: "3333"
          VITE_DEV_API_DOMAIN: "http://localhost:8181"

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
