apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "direktiv.fullname" . }}-config-functions
  labels:
    {{- include "direktiv.labels" . | nindent 4 }}
data:
  functions-config.yaml: |

      # address of flow engine
      flow-service: {{ include "direktiv.fullname" . }}-flow.{{ .Release.Namespace }}

      # redis for pub/sub
      redis-backend: {{ .Values.redis.address }}

      # maximum timeout, needs to be in below knative max
      request-timeout: 600

      # name of the service account to run the pods
      service-account: {{ include "direktiv.serviceAccountName" . }}-functions-pod

      # name of the namespace to use for the services/functions
      namespace: {{ .Values.functions.namespace }}

      # pod sidecar name
      sidecar: {{ .Values.functions.sidecar }}

      # init pod name
      init-pod: {{ .Values.functions.initPodImage }}

      # max number of revisions to keep per namespace or global
      keep-revisions: 3

      # max number of parallel jobs per namespace
      max-jobs: 5

      # kubernetes 1.20 auto cleans up jobs, for < 1.19, should be enabled
      pod-cleaner: {{ .Values.functions.podCleaner }}

      # max number of pods per service
      max-scale: 3

      # rollout seconds for knative services
      rollout-duration: 10

      # shaping network traffic if supported by network plugin
      net-shape: {{ .Values.functions.netShape }}

      # default concurrency level
      concurrency: 100

      # max ephemeral storage in MB
      storage: 100

      # runtime for services, e.g. gvisor
      runtime: {{ .Values.functions.runtime }}

      # memory/cpu value defined for different service sizes
      memory:
        small: 64
        medium: 128
        large: 256
      cpu:
        small: 0.1
        medium: 0.25
        large: 0.5

      # proxy values
      proxy:
        no: ""
        https: ""
        http: ""

      # grpc-config: {{ include "direktiv.fullname" . }}-config-grpc

      # additional sidecar containers
      additionalContainers:
{{- if .Values.functions.extraContainersPod }}
{{ toYaml .Values.functions.extraContainersPod | indent 8}}
{{- end }}
